services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_SENHA}"

    ports:
      - "1433:1433"

    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_SENHA}", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10
    
    volumes:
      - sql_data:/var/opt/mssql

  api:

    image: mcr.microsoft.com/dotnet/sdk:10.0

    working_dir: /src

    ports:
      - "5000:8080"

    depends_on:
      sqlserver:
          condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "${ConnectionStrings__Default}"
      JWT_KEY: "${JWT_KEY}"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"

    command: >
      bash -c "
        rm -rf bin obj &&
        dotnet restore &&
        dotnet watch --project ProjetoForms.csproj run --urls=http://0.0.0.0:8080
      "

    volumes:
      - .:/src

volumes:
  sql_data: